# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_title', models.CharField(max_length=200)),
                ('sections_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sections',
            },
        ),
    ]
