# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=200)),
                ('theme_date', models.DateTimeField()),
                ('theme_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Sections')),
            ],
            options={
                'db_table': 'Themes',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Themes'),
        ),
    ]
