# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20161217_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='sections_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='theme_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
